### ISSUE TITLE
FeatureProperty vs FeatureMember

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML-3.0Encodings#17]
It seems that there is an inconsistent way of modelling property types for nested features. For instance, the type `core:AbstractCityObjectType` can have both a list of `Appearance` and `Dynamizer` features as properties.

For `Appearance`, a property type is derived from `gml:AbstractFeatureMember`. For `Dynamizer`, a separate `DynamizerPropertyType` is defined which however is not derived from `gml:AbstractFeatureMember`. Since both feature types are derived from `core:AbstractFeatureWithLifespan`, I do not see the reason for the difference.

Moreover, using a `gml:AbstractFeatureMember` makes `core:AbstractCityObjectType` a feature collection. This does not feel right.

**Comment by TatjanaKutzner** [comment]
The encoding depends on whether an association or aggregation is encoded.

An aggregation is defined between `AbstractCityObject` and `Appearance`. 
Encoding rule E.2.4.11 from ISO 19136 says: "If an association role is the target end of an aggregation or composition, then the property type shall extend gml:AbstractMemberType". 
The rule is applied by ShapeChange in the encoding, however, somehow not correctly, as in our case the property type extends `gml:AbstractFeatureMemberType` and not `gml:AbstractMemberType`.

Between `AbstractCityObject` and `Dynamizer`, in contrast, an association is defined.
In this case, the property type of the Dynamizer feature type is used. This is also defined in rule E.2.4.11.

For each UML class with the stereotype `<<FeatureType>>` a property type is created by default during the encoding. See encoding rule E.2.4.6: "A named complex type shall be created for these classes (carrying the name of the class with a “PropertyType” suffix), if the class does not carry a tagged value "noPropertyType" with the value "true"."
Thus, there is the property type `DynamizerPropertyType` for the UML class `Dynamizer`. 
These property types do not have extensions.

We should discuss, whether we want these different encodings.
Or how we could solve this, e.g. by implementing an exception to the rule.

**Comment by clausnagel** [comment]
Ok, thanks. Hm, then why not use associations instead of aggregations?

And why has the `AbstractFeatureMember` from `AbstractCityObject` to `Appearance` the `gml:AssociationAttributeGroup`, whereas similar aggregations like the one from `AbstractBuilding` to `BuildingConstructiveElement` lacks this attribute group. In general, I would prefer the latter because it forbids XLinks.

**Comment by clausnagel** [comment]
What about this rule:

1. If a nested feature shall only be given inline and not by-reference, then use aggregation / composition in the UML. In the GML encoding, the property element shall then extend `AbstractFeatureMemberType` but without adding `gml:AssociationAttributeGroup`.

2. If a nested feature can be given inline or by reference, then an association shall be used in the UML. In this case, the property element in the GML encoding shall use the `...PropertyType` generated for the class.

This would help implementers a lot because `AbstractFeatureMemberType` and `...PropertyType` have a distinct use case and are not arbitrarily mixed as in the current draft.

**Comment by TatjanaKutzner** [comment]
Your first rule is exactly the reason, why the aggregaction from `AbstractBuilding` to `BuildingConstructiveElement` lacks the attribute group. The tagged value is set to `inline` here. 

Yes, I think the rules would make sense. No changes to ShapeChange would be required, thus, we will be compliant to ISO 19136 and, in addition, it would also be possible to see directly from the UML diagram which features have to be provided inline and which features can be provided either inline or by reference.

**Comment by TatjanaKutzner** [comment]
Claus and I discussed that the issue can be closed. The different encodings of associations and aggregations are due to the ISO 19136 encoding rule. Also, the UML model has already been finalised, so that we cannot apply changes to the UML model any more.
