### ISSUE TITLE
Incorrect xs:import in cityGMLBase.xsd

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML-3.0Encodings#19]
The schema `cityGMLBase.xsd` uses the following `xs:import` to import the PointCloud module:

```xml
<import namespace="http://www.opengis.net/citygml/pointcloud/3.0" schemaLocation="./pointcloud.xsd"/>
```

However, the filenames of all CityGML schemas use lower camel case. Thus, the filename of the PointCloud schema is `pointCloud.xsd` (with a capital 'C') instead of `pointcloud.xsd`. This must be corrected.

(Note: the Core module should not import PointCloud at all because this creates a dependency of the Core on an optional module. But this requires more rework of the schemas)

**Comment by TatjanaKutzner** [comment]
Was already fixed, see commit 0edea4c93d4e3357787f6ccf5a51b70841e33e01 in the editor-model-updates branch.

**Comment by clausnagel** [comment]
Thanks Tatjana, nice. I nevertheless keep this issue open because of my second comment that Core should not import PointCloud.

**Comment by TatjanaKutzner** [comment]
Second comment has been solved long time ago.
