### ISSUE TITLE
Relax fixed sequence of CityModel member properties

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML-3.0Encodings#38]
The current draft GML schema for the core module defines a fixed `<xs:sequence>` for all member properties of a `<CityModel>` such as `<cityObjectMember>`, `<apperanceMember>` or `<featureMember>`. Although this is technically OK, it is different to CityGML 2.0 where all the member properties were defined as substitutes of `gml:featureMember` and thus could occur in an arbitrary order within a dataset.

Especially when writing software to convert exisiting CityGML 2.0 datasets to the new version 3.0, the fixed sequence is annoying because you cannot simply iterate over all members of the `<CityModel>` and write them to the target file. You would first have to collect and group all members by their type (i.e. cityObjectMember,  apperanceMember, featureMember) to be able to write them in the proper sequence. If you work on large input files, you might not be able to process the data in main memory, and thus things quickly become very tricky.

To make the life of implementers more easy, I suggest to replace the `<xs:sequence>` with a `<xs:choice>` in the GML schema. This would resolve the fixed ordering of member properties.

**Comment by TatjanaKutzner** [comment]
It is possible to solve this issue by introducing in the UML model a new class `CityModelMember` with the stereotype `<<Union>>` that defines alle the member properties. `<<Union>>` classes are encoded by default using `<xs:choice>`. The class `CityModel` is associated with this new class and does not contain any more individual member property associations.
![grafik](https://user-images.githubusercontent.com/5949401/73543330-ffdfc800-4436-11ea-9877-a57e327d3777.png)

To avoid that the new class is encoded as additional XML element, the tagged value `gmlAsGroup=true` is added to the class. In addition, the encoding rule `rule-xsd-cls-union-asGroup` is added to the ShapeChange configuration file. In this way, the `<<Union>>` class is encoded as global group that can be referenced by `<CityModel>`.

**Comment by clausnagel** [comment]
fixed in 32e3d60680d56e4ca1c254876e107992eea733b9
