### ISSUE TITLE
Point Cloud Example File/Folder Names Too Long

### ISSUE THREAD

**Issue by 3DXScape** [opengeospatial/CityGML-3.0Encodings#55]
I cannot clone the repo because the names are too long when concatenated. Can these be shortened?

**Comment by 3DXScape** [comment]
Here is an example

CityGML-3.0Encodings/CityGML/Examples/PointCloud/Real-world examples/CityGML_3.0_buildings_with_point_cloud_representation/Buildings_CityGML3.0_LOD2_with_PointClouds_inline/

**Comment by 3DXScape** [comment]
Log with details:

Cloning into 'D:\Git\CityGML-3.0Encodings'...
remote: Enumerating objects: 1962, done.        
remote: Counting objects: 100% (1066/1066), done.        
remote: Compressing objects: 100% (999/999), done.        
remote: Total 1962 (delta 199), reused 883 (delta 65), pack-reused 896        
Receiving objects: 100% (1962/1962), 70.30 MiB | 2.06 MiB/s, done.
Resolving deltas: 100% (775/775), done.
error: unable to create file CityGML/Examples/PointCloud/Real-world examples/CityGML_3.0_buildings_with_point_cloud_representation/Buildings_CityGML3.0_LOD2_with_PointClouds_external_individual_laz_files/Buildings_CityGML3.0_LOD2_with_PointClouds_external_individual_laz_files.gz: Filename too long
error: unable to create file CityGML/Examples/PointCloud/Real-world examples/CityGML_3.0_buildings_with_point_cloud_representation/Buildings_CityGML3.0_LOD2_with_PointClouds_external_one_laz_file/Buildings_CityGML3.0_LOD2_with_PointClouds_external_one_laz_file.gz: Filename too long
Updating files: 100% (933/933), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by clausnagel** [comment]
As a workaround, you can try and use `git config core.longpaths true` in the cloned repo.

**Comment by 3DXScape** [comment]
`git config core.longpaths true` solved my immediate problem, thank you.
