### ISSUE TITLE
I tried to use ADE to extend Building properties, but I didn't know how to write a Schema file

### ISSUE THREAD

**Issue by caidc** [opengeospatial/CityGML-3.0Encodings#65]
I tried to use ADE to extend Building properties, but I didn't know how to write a Schema file

**Comment by nob140** [comment]
Hi caidc,
The draft document below would be help for you. Those are explaining how to use ADE of CityGML 3.0 GML Encoding.
https://github.com/nob140/CityGML3_ADE/blob/main/document/annex-examples-ADE-realworld.adoc
https://github.com/nob140/CityGML3_ADE

**Comment by caidc** [comment]
Thank you very much.This is very helpful to me.

**Comment by nob140** [comment]
Hi caidc,
Please note that the contents are subject to change.
BTW, could you please close this issue? Thanks!
