### ISSUE TITLE
FZKViewer error when trying to read gml:OrientableSurface

### ISSUE THREAD

**Issue by DiegoVinasco** [opengeospatial/CityGML-3.0Encodings#67]
When trying to load [the LOD3 converted example from CityGML 2.0](https://github.com/opengeospatial/CityGML-3.0Encodings/blob/master/CityGML/Examples/Examples-from-CityGML-2.0/building/CityGMLv3/Building_LOD3-EPSG25832.gml) in FZKViewer v6.3 I came across the following error:

![image](https://user-images.githubusercontent.com/23373264/161566777-7c17f9d1-18e2-482f-af33-e0572c8ea3e6.png)

All of the other examples loaded just fine including [the original CityGML 2.0 representation](https://github.com/opengeospatial/CityGML-3.0Encodings/blob/e0eea4d0756753575506c704c84501fb798da6a7/CityGML/Examples/Examples-from-CityGML-2.0/building/CityGMLv2/Building_LOD4-EPSG25832.gml#L426) of the building which also uses `gml:OrientableSurface`.

**Comment by clausnagel** [comment]
Thanks for testing, @DiegoVinasco. I am not sure about the conclusion though, because the FZKViewer does not officially support CityGML 3.0 yet. So, might be an internal software error.

**Comment by DiegoVinasco** [comment]
Right, I was thinking that was the case. I'll close the issue then.
